Added gitlab social link and svg icon
sergiokopplin/indigo pull request #308
Opened 2018-06-09 23:11 UTC by antenore

As many are moving to gitlab I thought it would make sense and logical to propose this patchset.

Thanks for your great work!!!

Rendered example:

![image](https://user-images.githubusercontent.com/5975/41196856-33dcacce-6c4b-11e8-801f-48bc89ef11c5.png)

2018-06-11 21:35 UTC, sergiokopplin requested changes

2018-06-11 21:35 UTC, sergiokopplin commented on _config.yml
> +gitlab: mygitlab
Can you put that as a comment? Gracias!

2018-06-12 08:12 UTC, antenore commented on _config.yml
> +gitlab: mygitlab
Done, thanks

2018-06-12 14:57 UTC, merged

2018-06-12 14:57 UTC, sergiokopplin commented
Thanks!